// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package providers

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSongGetter creates a new instance of MockSongGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSongGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSongGetter {
	mock := &MockSongGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSongGetter is an autogenerated mock type for the SongGetter type
type MockSongGetter struct {
	mock.Mock
}

type MockSongGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSongGetter) EXPECT() *MockSongGetter_Expecter {
	return &MockSongGetter_Expecter{mock: &_m.Mock}
}

// ScrapePlaylist provides a mock function for the type MockSongGetter
func (_mock *MockSongGetter) ScrapePlaylist(ctx context.Context, source string) ([]byte, error) {
	ret := _mock.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for ScrapePlaylist")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSongGetter_ScrapePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScrapePlaylist'
type MockSongGetter_ScrapePlaylist_Call struct {
	*mock.Call
}

// ScrapePlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
func (_e *MockSongGetter_Expecter) ScrapePlaylist(ctx interface{}, source interface{}) *MockSongGetter_ScrapePlaylist_Call {
	return &MockSongGetter_ScrapePlaylist_Call{Call: _e.mock.On("ScrapePlaylist", ctx, source)}
}

func (_c *MockSongGetter_ScrapePlaylist_Call) Run(run func(ctx context.Context, source string)) *MockSongGetter_ScrapePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSongGetter_ScrapePlaylist_Call) Return(bytes []byte, err error) *MockSongGetter_ScrapePlaylist_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSongGetter_ScrapePlaylist_Call) RunAndReturn(run func(ctx context.Context, source string) ([]byte, error)) *MockSongGetter_ScrapePlaylist_Call {
	_c.Call.Return(run)
	return _c
}
