// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package providers

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/jbenzshawel/playlist-generator/internal/app/commands/playlists/spotify/models"
)

// NewMockPlaylistTrackGetter creates a new instance of MockPlaylistTrackGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlaylistTrackGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlaylistTrackGetter {
	mock := &MockPlaylistTrackGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlaylistTrackGetter is an autogenerated mock type for the TrackGetter type
type MockPlaylistTrackGetter struct {
	mock.Mock
}

type MockPlaylistTrackGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlaylistTrackGetter) EXPECT() *MockPlaylistTrackGetter_Expecter {
	return &MockPlaylistTrackGetter_Expecter{mock: &_m.Mock}
}

// GetPlaylistTracks provides a mock function for the type MockPlaylistTrackGetter
func (_mock *MockPlaylistTrackGetter) GetPlaylistTracks(ctx context.Context, playlistID string, limit int, offset int) (models.PlaylistTrackPage, error) {
	ret := _mock.Called(ctx, playlistID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPlaylistTracks")
	}

	var r0 models.PlaylistTrackPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) (models.PlaylistTrackPage, error)); ok {
		return returnFunc(ctx, playlistID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) models.PlaylistTrackPage); ok {
		r0 = returnFunc(ctx, playlistID, limit, offset)
	} else {
		r0 = ret.Get(0).(models.PlaylistTrackPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, playlistID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistTrackGetter_GetPlaylistTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlaylistTracks'
type MockPlaylistTrackGetter_GetPlaylistTracks_Call struct {
	*mock.Call
}

// GetPlaylistTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID string
//   - limit int
//   - offset int
func (_e *MockPlaylistTrackGetter_Expecter) GetPlaylistTracks(ctx interface{}, playlistID interface{}, limit interface{}, offset interface{}) *MockPlaylistTrackGetter_GetPlaylistTracks_Call {
	return &MockPlaylistTrackGetter_GetPlaylistTracks_Call{Call: _e.mock.On("GetPlaylistTracks", ctx, playlistID, limit, offset)}
}

func (_c *MockPlaylistTrackGetter_GetPlaylistTracks_Call) Run(run func(ctx context.Context, playlistID string, limit int, offset int)) *MockPlaylistTrackGetter_GetPlaylistTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPlaylistTrackGetter_GetPlaylistTracks_Call) Return(playlistTrackPage models.PlaylistTrackPage, err error) *MockPlaylistTrackGetter_GetPlaylistTracks_Call {
	_c.Call.Return(playlistTrackPage, err)
	return _c
}

func (_c *MockPlaylistTrackGetter_GetPlaylistTracks_Call) RunAndReturn(run func(ctx context.Context, playlistID string, limit int, offset int) (models.PlaylistTrackPage, error)) *MockPlaylistTrackGetter_GetPlaylistTracks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrackSearcher creates a new instance of MockTrackSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackSearcher {
	mock := &MockTrackSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrackSearcher is an autogenerated mock type for the TrackSearcher type
type MockTrackSearcher struct {
	mock.Mock
}

type MockTrackSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackSearcher) EXPECT() *MockTrackSearcher_Expecter {
	return &MockTrackSearcher_Expecter{mock: &_m.Mock}
}

// SearchTrack provides a mock function for the type MockTrackSearcher
func (_mock *MockTrackSearcher) SearchTrack(ctx context.Context, artist string, track string, album string) (models.SearchTrackResponse, error) {
	ret := _mock.Called(ctx, artist, track, album)

	if len(ret) == 0 {
		panic("no return value specified for SearchTrack")
	}

	var r0 models.SearchTrackResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (models.SearchTrackResponse, error)); ok {
		return returnFunc(ctx, artist, track, album)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) models.SearchTrackResponse); ok {
		r0 = returnFunc(ctx, artist, track, album)
	} else {
		r0 = ret.Get(0).(models.SearchTrackResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, artist, track, album)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackSearcher_SearchTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTrack'
type MockTrackSearcher_SearchTrack_Call struct {
	*mock.Call
}

// SearchTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - artist string
//   - track string
//   - album string
func (_e *MockTrackSearcher_Expecter) SearchTrack(ctx interface{}, artist interface{}, track interface{}, album interface{}) *MockTrackSearcher_SearchTrack_Call {
	return &MockTrackSearcher_SearchTrack_Call{Call: _e.mock.On("SearchTrack", ctx, artist, track, album)}
}

func (_c *MockTrackSearcher_SearchTrack_Call) Run(run func(ctx context.Context, artist string, track string, album string)) *MockTrackSearcher_SearchTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTrackSearcher_SearchTrack_Call) Return(searchTrackResponse models.SearchTrackResponse, err error) *MockTrackSearcher_SearchTrack_Call {
	_c.Call.Return(searchTrackResponse, err)
	return _c
}

func (_c *MockTrackSearcher_SearchTrack_Call) RunAndReturn(run func(ctx context.Context, artist string, track string, album string) (models.SearchTrackResponse, error)) *MockTrackSearcher_SearchTrack_Call {
	_c.Call.Return(run)
	return _c
}
