// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package provider

import (
	mock "github.com/stretchr/testify/mock"
)

// newMocksongGetter creates a new instance of mocksongGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksongGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksongGetter {
	mock := &mocksongGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksongGetter is an autogenerated mock type for the songGetter type
type mocksongGetter struct {
	mock.Mock
}

type mocksongGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksongGetter) EXPECT() *mocksongGetter_Expecter {
	return &mocksongGetter_Expecter{mock: &_m.Mock}
}

// ScrapePlaylist provides a mock function for the type mocksongGetter
func (_mock *mocksongGetter) ScrapePlaylist(source string) ([]byte, error) {
	ret := _mock.Called(source)

	if len(ret) == 0 {
		panic("no return value specified for ScrapePlaylist")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(source)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksongGetter_ScrapePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScrapePlaylist'
type mocksongGetter_ScrapePlaylist_Call struct {
	*mock.Call
}

// ScrapePlaylist is a helper method to define mock.On call
//   - source string
func (_e *mocksongGetter_Expecter) ScrapePlaylist(source interface{}) *mocksongGetter_ScrapePlaylist_Call {
	return &mocksongGetter_ScrapePlaylist_Call{Call: _e.mock.On("ScrapePlaylist", source)}
}

func (_c *mocksongGetter_ScrapePlaylist_Call) Run(run func(source string)) *mocksongGetter_ScrapePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksongGetter_ScrapePlaylist_Call) Return(bytes []byte, err error) *mocksongGetter_ScrapePlaylist_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mocksongGetter_ScrapePlaylist_Call) RunAndReturn(run func(source string) ([]byte, error)) *mocksongGetter_ScrapePlaylist_Call {
	_c.Call.Return(run)
	return _c
}
